### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by alfonsogarciacaro** [MangelMaxime/Thot#1]
Copy & pasted from Slack so I don't forget ;)

[This test](https://github.com/MangelMaxime/Thot/blob/773b5e031f17d942efd5ceed69ef9512f16121fe/tests/Tests.Json.Decode.fs#L650) is failing. It's probably related to how Fable translate the [custom](https://github.com/MangelMaxime/Thot/blob/773b5e031f17d942efd5ceed69ef9512f16121fe/src/Json/Decode.fs#L395) function.

You can debug doing: `./build.sh DotnetBuild`, in a terminal : `yarn run test` and in another `yarn run mocha ./tests/bin/` or press F5 into VSCode to be able to set breakpoint.

**Comment by MangelMaxime** [comment]
The latest message of @inosik in this issue https://github.com/fable-compiler/Fable/issues/1199#issuecomment-347101093 about:

> "thenAdd2 is not a function"

make me think of the error we are facing this project. Perhaps, I am using the point-free style without knowing it.

**Comment by alfonsogarciacaro** [comment]
I just tried with Fable development version and the test passed 😸 I will release Fable 1.3.3 so you can give it a try.

I also got a warning message [about this line](https://github.com/MangelMaxime/Thot/blob/773b5e031f17d942efd5ceed69ef9512f16121fe/src/Json/Decode.fs#L405) so I recommend changing it to `let decode x y = succeed x y` 👌

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Awesome, so this was somehow related to the linked issue probably.

Yes, I was in the process to add explicit arguments in every function. Thanks you :)

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro [This line](https://github.com/MangelMaxime/Thot/blob/wip/tests/Tests.Json.Decode.fs#L657) seems to be failing now :)

And what I found strange is that it don't execute the function I am expecting.

If you look at the [`optional`](https://github.com/MangelMaxime/Thot/blob/wip/src/Json/Decode.fs#L432-L433) decoder. You can see it's using internally the [`value`](https://github.com/MangelMaxime/Thot/blob/wip/src/Json/Decode.fs#L246) decoder which is the most basic decoder. It is use to accept any type of data and transform the express into a valid [`decoder`](https://github.com/MangelMaxime/Thot/blob/wip/src/Json/Decode.fs#L52) type.

Problem, is the variable `value` at [this point](https://github.com/MangelMaxime/Thot/blob/wip/src/Json/Decode.fs#L415) is undefined. I don't understand why the `value` decoder is not called by the code. Is it related to how Fable translate the curriedfn ?

**Comment by MangelMaxime** [comment]
Hum, I think I know where the error is coming from.

The probably is coming from [`field`](https://github.com/MangelMaxime/Thot/blob/wip/src/Json/Decode.fs#L147-L153). When called as in the failing test, the result of:

`let fieldValue = value?(fieldName)` is `curriedFn` because `value` is not an object but a function.

Here is the result of `value.ToString()`:


```js
(...args) => {
        // _this = _this || this;
        const actualArgsLength = Math.max(args.length, 1);
        expectedArgsLength = Math.max(expectedArgsLength || f.length, 1);
        if (actualArgsLength >= expectedArgsLength) {
            const restArgs = args.splice(expectedArgsLength);
            const res = f(...args);
            if (typeof res === "function") {
                const newLambda = CurriedLambda(res);
                return restArgs.length === 0 ? newLambda : newLambda(...restArgs);
            }
            else {
                return res;
            }
        }
        else {
            return CurriedLambda((...args2) => {
                return f(...args.concat(args2));
            }, expectedArgsLength - actualArgsLength);
        }
    }
```

And if I execute, the function manually in the debugger I understand that's it's containing the [`value`](https://github.com/MangelMaxime/Thot/blob/wip/src/Json/Decode.fs#L246) function.

Example result: `value() --> Result {tag: 0, data: undefined}`

The right value for the `value` variable in this case is: `{ "id": 67, "email": "user@mail.com" }`

Yes, I admit there a lot of time "value" in this report..

**Comment by MangelMaxime** [comment]
Ok finally I only forget to apply `andThen` instead of `|>` on the `optionalDecoder` :man_facepalming:
