### ISSUE TITLE
hardcoded: Warning about point-free style

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Thot#13]
@alfonsogarciacaro I am having the warning about point-free style on the [`hardcoded`](https://github.com/MangelMaxime/Thot/blob/master/src/Thot.Json/Decode.fs#L432) decoder. But I think, we should allow this function style no ?

I also, don't know how to rewrite it to mimic the `>>` operator and so remove the point-free style. Can you please help me to removed the warning one way or another ?

Error:
> fable: Compiled src/Thot.Json/Encode.fs
(!) fable plugin: /home/mangelmaxime/Workspaces/Github/MangelMaxime/Fable.Json/src/Thot.Json/Decode.fs(432,4): (432,13) warning FABLE: Looks like Thot.Json.Decode.hardcoded uses point-free style, this may create problems in runtime, please declare all arguments explicitly.

**Comment by alfonsogarciacaro** [comment]
In latest Fable version the warning is removed again, sorry! 😅 

You could use something like this (with better parameter names):

```fsharp
let hardcoded<'a, 'b, 'c> (x: 'a) (y: Decoder<('a -> 'b)>) (z: 'c) (u: Result<'b,DecoderError>) v =
    succeed v |> custom
```

But even like that dynamic CurriedLambdas are still being generated so I guess it doesn't really matter:

```js
// let hardcoded<'a, 'b, 'c> : 'a -> Decoder<('a -> 'b)> -> 'c -> Result<'b,DecoderError> = succeed >> custom
function hardcoded() {
    return CurriedLambda($var3 => CurriedLambda(function (d1, d2) {
        return custom(d1, d2);
    })(($var1 => $var2 => function (output, arg10_) {
        return succeed(output, arg10_);
    }($var1, $var2))($var3)));
}

// let hardcoded<'a, 'b, 'c> (x: 'a) (y: Decoder<('a -> 'b)>) (z: 'c) (u: Result<'b,DecoderError>) v =
//    succeed v |> custom
function hardcoded(x, y, z, u, v) {
    return CurriedLambda(CurriedLambda(function (d1, d2) {
        return custom(d1, d2);
    })(function (arg10_) {
        return succeed(v, arg10_);
    }));
}
```

**Comment by MangelMaxime** [comment]
Thanks you :) will try it and update dependencies to the latest version too

**Comment by MangelMaxime** [comment]
I am closing as Fable don't generate warning now.

I just don't know how to write the composition etc. by hand. For now, it's not problems because no warning is output :)
