### ISSUE TITLE
Encode a list with Thot.json

### ISSUE THREAD

**Issue by whitetigle** [MangelMaxime/Thot#16]
Hi!
I'm having troubles decoding a list with the decoder.
The list exists in my json object, but since I encode it manually without Thot, maybe the format is not good and cannot be decoded?

Anyway, since I need to send a JS object to my store, I use the following unsafe method:
```f#
        createObj  [
          "mylist" ==> object.someList
        ]
```

where `someList` is an **optional** list field

So using Thot.Encode, how would that work? Furthermore, would I be possible to output a JS object?
Thanks in advance for your help!

**Comment by MangelMaxime** [comment]
I am not sure to understand your problem, `encore` function will output a `string` not a `JS object`.

Does the following code answer your question ?

```fs
open Thot.Json

let listData = Some  []

let fromOption data =
    match data with
    | Some data ->
        Encode.list [ ] // Decode here the list via a for loop for example
    | None -> Encode.nil

let jsonString =
    Encode.object
        [ "myList", fromOption listData
        ]

```

**Comment by whitetigle** [comment]
To add even mode details, a list in a JS Object using createObj looks like this:
`"myList":{"head":{"field":"value","otherfield","value"},"tail":{}}`

So maybe I would have to provide some custom decoder for the list type to handle head and tail values? Or is it already handled by thot?

**Comment by whitetigle** [comment]
Thanks for your fast answer!  👍 
I will try the method you gave me and tell you if that works.

**Comment by whitetigle** [comment]
Ok so, since I **must** send a JS Object that will be serialized by the library using JS.Stringify, I need to transform my list into an array so that I don't get the List custom tails and head fields. And then it works.

So, well it had nothing to do with Thot. 
As always, thanks for your kind help @MangelMaxime 👏
