### ISSUE TITLE
Create Map decoder

### ISSUE THREAD

**Issue by rommsen** [MangelMaxime/Thot#3]
Thanks for the library. 

We need to decode into a F# Map. In Elm I would use http://package.elm-lang.org/packages/elm-lang/core/latest/Json-Decode#dict . What would be necessary to implement this in Thot?

**Comment by MangelMaxime** [comment]
This need to implement a decoder. Like we did for `list`, `index`, etc. I will try to work on it :)

Do you have a Json that I can use as an example ? And the corresponding `Map` ?
