### ISSUE TITLE
Fix docs site for responsive display

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Thot#6]

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro @rommsen I have updated the docs site to support mobile device.

On really small screen the content of the page can still be hard to read, but not sure, how to improve it because it's the width the problem :)

Can you please test that's it's working ? And if you still have problems, feel free to re-open this issue :)

**Comment by alfonsogarciacaro** [comment]
It looks fine on my mobile, great work! :clap:

**Comment by rommsen** [comment]
Looks much better. Nice!
